### PR TITLE
use legacy pip resolver for pip versions < 21.1 > 20.2.4

### LINKED ISSUE #638: puppet tries to install latest version of a pip package on every run
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6
- Ruby: 2.7
- Distribution: Debian Bullseye 
- Module version: 6.3.0

## How to reproduce (e.g Puppet code you use)
`ensure_resource('python::pip', 'check-systemd', {'ensure' => 'latest', 'pip_provider' => 'pip3'})`

## What are you seeing
Puppet tries to install the package on each run

## What behaviour did you expect instead
Puppet tries to install the package only once

## Output log
`Notice: /Stage[main]/Profile::Base::Common/Python::Pip[check-systemd]/Exec[pip_install_check-systemd]/returns: executed successfully (corrective)`

## Any additional information you'd like to impart
`pip` changed the dependency resolver in version 20.3. There's more information here: https://stackoverflow.com/a/26664162
As the command to find the latest version is returning an error instead of version numbers, there is no latest version available and that's why puppet tries to install the package on each run

Looks like as if we need to use a different command, depending on the pip version.

pip 20.3.4:
```
root@machine ~ # pip install --use-deprecated=legacy-resolver check-systemd==
ERROR: Could not find a version that satisfies the requirement check-systemd== (from versions: 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.3.1)
ERROR: No matching distribution found for check-systemd==
```

pip 20.0.2:
```
root@machine:~# pip install check-systemd==
ERROR: Could not find a version that satisfies the requirement check-systemd== (from versions: 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.3.1)
ERROR: No matching distribution found for check-systemd==
```

pip 20.1.1:
```
root@machine:~# pip install check-systemd==
ERROR: Could not find a version that satisfies the requirement check-systemd== (from versions: 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.3.1)
ERROR: No matching distribution found for check-systemd==
```

pip 19.1.1:
```
root@machine:~# pip install check-systemd==
Collecting check-systemd==
  ERROR: Could not find a version that satisfies the requirement check-systemd== (from versions: 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.3.1)
ERROR: No matching distribution found for check-systemd==
```

pip 22.0.4:
```
root@machine:~# pip install check-systemd==
ERROR: Could not find a version that satisfies the requirement check-systemd== (from versions: 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.3.1)
ERROR: No matching distribution found for check-systemd==
```

### PR DESCRIPTION
**Pull request by saz**
#### Pull Request (PR) description
This PR adds the flag `--use-deprecated=legacy-resolver` to pip install commands, if pip version is below 21.1 and higher than 20.2.4

#### This Pull Request (PR) fixes the following issues
Fixes #638

### CODE REVIEW

File: spec/defines/pip_spec.rb [hunk 1]
```diff
@@ -144,6 +151,34 @@
...
     end
   end
+
+  context 'on Debian OS with pip_version 20.3.4' do
+    let :facts do
+      {
+        id: 'root',
+        kernel: 'Linux',
+        lsbdistcodename: 'squeeze',
+        os: {
```
Comment (bastelfreak) [inline spec/defines/pip_spec.rb:161]: could you instead mock an OS that we currently support? (we should really rewrite the whole file to use rspec-puppet-facts...)

File: spec/defines/pip_spec.rb [hunk 2]
```diff
@@ -144,6 +151,34 @@
...
+        concat_basedir: '/dne',
+        pip_version: '20.3.4'
+      }
+    end
+
+    describe 'install latest' do
+      context 'with legacy resolver in unless cmd' do
+        let(:params) { { ensure: 'latest' } }
+
+        it { is_expected.to contain_exec('pip_install_rpyc').with_unless(%r{--use-deprecated=legacy-resolver}) }
```
Comment (bastelfreak) [inline spec/defines/pip_spec.rb:178]: please also add something like
```puppet
it { is_expected.to compile.with_all_deps }
```

File: spec/defines/pip_spec.rb (hunk 1 above)
Comment (saz) [reply spec/defines/pip_spec.rb:161]: Sure! I'll see what I can do after this PR :-)

**Comment by bastelfreak** [comment]
@saz can you please rebase against our latest master to get rid of the merge commit?

**Comment by saz** [comment]
I did that yesterday and don't see any conflict? :thinking:
